version: '3.9'

services:
  rabbit:
    restart: always
    image: rabbitmq:3-management
    ports:
      - "15672:15672"
      - "5672:5672"
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 15s
      timeout: 10s
      retries: 5
    networks:
      - rabbit_network  

  publisher-service:
    restart: on-failure
    env_file:
      - variables.env
    build:
      context: .
      dockerfile: src/PublisherService/Dockerfile
    ports:
      - "5000:8080"
    depends_on:
      rabbit:
        condition: service_healthy
    networks:
      - rabbit_network    
    
  message-processor:
     restart: on-failure
     env_file:
       - variables.env
     build:
       context: .
       dockerfile: src/MessageProcessor/Dockerfile
     depends_on:
       rabbit:
         condition: service_healthy
     networks:
       - rabbit_network

networks:
  rabbit_network:
   
