version: '3.4'

services:
  rabbit:
    restart: always
    image: rabbitmq:3-management
    ports:
      - "15672:15672"
      - "5672:5672"
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 15s
      timeout: 10s
      retries: 5

  publisherservice:
    restart: on-failure
    image: ${DOCKER_REGISTRY-}publisherservice
    env_file:
      - variables.env
    build:
      context: .
      dockerfile: src/PublisherService/Dockerfile
    ports:
      - "5000:80"
      - "44388:443"
    depends_on:
      rabbit:
        condition: service_healthy

  messageprocessorconsoleservice:
    restart: on-failure
    image: ${DOCKER_REGISTRY-}messageprocessorconsoleservice
    env_file:
      - variables.env
    build:
      context: .
      dockerfile: src/MessageProcessorConsoleService/Dockerfile
    depends_on:
      rabbit:
        condition: service_healthy
